# Generated by Django 6.1 on 2026-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен'), ('no_payment_required', 'Оплата не требуется')], default='unpaid', max_length=20, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id цены в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id продукта в Stripe'),
        ),
    ]
