[tool.poetry]
name = "pythonproject11"
version = "0.1.0"
description = ""
authors = ["Eugen <trushin00332211@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
django = "^6.1"
djangorestframework = "^3.18.0"
pillow = "^12.3.0"
django-filter = "^26.1"
djangorestframework-simplejwt = "^5.5.1"
drf-spectacular = {extras = ["sidecar"], version = "^0.30.0"}
stripe = "^15.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "coverage (>=7.16.0,<8.0.0)"
]

[tool.coverage.run]
source = ["config", "lms", "users"]
omit = [
    "*/migrations/*",
    "*/tests.py",
]

[tool.coverage.report]
show_missing = true
