# Generated by Django 6.1 on 2026-09-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_course_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
